### ISSUE TITLE
Yahoo! Finance API broken?

### ISSUE THREAD

**Issue by diegotrazzi** [matplotlib/mpl_finance#11]
mpl_finance/examples/longshort.py

on line 13, seems that ichart on yahoo finance has been discontinued or is down : 

https://forums.yahoo.net/t5/Yahoo-Finance-help/Is-Yahoo-Finance-API-broken/td-p/250503/page/25

**Comment by tacaswell** [comment]
Yes, the yahoo API appears to change regularly and we can not keep up :(

**Comment by diegotrazzi** [comment]
Thanks for taking the tame to reply the tickets! Have a nice day !

**Comment by lukaszo** [comment]
Actually Yahoo removed their API

**Comment by efiring** [comment]
Given that the Yahoo API has been removed, I am closing this issue.
