### ISSUE TITLE
What is different from matplotlib.finance ? 

### ISSUE THREAD

**Issue by diegotrazzi** [matplotlib/mpl_finance#12]
The official guide mentions the old finance module is deprecated and has been moved to mpl_finance.
Is anything actually different, or is there a good reasons for adding this additional library, since it doesn't come with matplotlib ?

**Comment by tacaswell** [comment]
If you want the finance-specific plotting then you will need to install this library.

**Comment by jorgeog96** [comment]
This package includes volume_overlay module from the deprecated finance?

**Comment by a-watson** [comment]
@jorgeog96, yes I believe the only functionality removed was pulling data from Yahoo Finance. volume_overlay is still present.

**Comment by 1rocketdude** [comment]
I can confirm that it's a drop in replacement. After resisting the upgrade from Matplotlib 2.1.2, I used the mpl_finance class and it works with Matplotlib 2.2.0.

**Comment by AdamHanafi** [comment]
why is candlestick_ohlc not identifiable when ran? I have mpl_finance packages on top of matplotlib

**Comment by DanielGoldfarb** [comment]
https://pypi.org/project/mplfinance/

( see also https://github.com/matplotlib/mplfinance#oldapi )
