### ISSUE TITLE
candlestick2_ohlc plotting alignment problem

### ISSUE THREAD

**Issue by andyfcx** [matplotlib/mpl_finance#13]
While using candlestick2_ohlc plotting, the starting point and the ending point are not located at the origin, left some space.

Is there any way to set the start at the origin?

![2010_2011_k-plot](https://user-images.githubusercontent.com/11717383/38611470-538a6f5c-3db6-11e8-9840-a9680dced099.png)

**Comment by efiring** [comment]
Assuming your first argument is the Axis object, `ax`, you can use 
```python
ax.margin(x=0)
```
or equivalently
```python
ax.set_xmargin(0)
```
The default can be controlled via a matplotlibrc file, or by directly setting
```python
plt.rcParams['axes.xmargin'] = 0
```
