### ISSUE TITLE
adding time functionality

### ISSUE THREAD

**Issue by wlblount** [matplotlib/mpl_finance#16]
i know this is not maintained but how big of a deal would it be to add time functionality to the existing bar and candle functions to handle intra-day plotting (or create new functions based on the existing ones)?  I am happy to help where I can,  more of a user than coder... the source code is a little beyond my ability.  Thanks.  Bill

**Comment by DanielGoldfarb** [comment]
This is definitely do-able.   I just started work on a new API for mpl-finance that will be higher level, doing a lot of things automatically for you (so, for example, the caller won't have to format the x-axis for date or time, but the API will figure out whether to use date or time and adjust the graph accordingly).  My goal is to make it simpler to use.  I am hoping to have a first cut ready for beta testing in another 5 to 10 days.  In the meantime, with a bit of work the existing API can be used for intraday data; for example, see the following gist: [mpl_finance_issue24](https://gist.github.com/DanielGoldfarb/0ca6af1d11a9fdaf51bc2847be5646b8)

**Comment by DanielGoldfarb** [comment]
Intraday / time functionality is now available in the new API.
Please see here:  https://github.com/matplotlib/mplfinance/blob/master/README.md
And here:  https://github.com/matplotlib/mplfinance/blob/master/examples/mplfinance_plot.ipynb
