### ISSUE TITLE
Do a "proper" release

### ISSUE THREAD

**Issue by NelleV** [matplotlib/mpl_finance#2]
See matplotlib/matplotlib#7524

**Comment by hajderr** [comment]
Wonder if anyone could shed some light on this since I'm confused with regards to the status of 7524, it says merged while this issue is still open. I tried searching for mpl_finance/finance through pip but no result.

**Comment by tacaswell** [comment]
We are looking for a maintainer for mpl-finance, one of that person's first jobs would be to do a release and get it on pypi.

**Comment by MarvinLer** [comment]
@tacaswell Did you find someone ?

**Comment by tacaswell** [comment]
No, not yet

**Comment by chrisjeffries24** [comment]
this is sad...I can't keep up

**Comment by DanielGoldfarb** [comment]
I did the packaging and release tutorial yesterday, and practiced using the test.pypi server.  My goal, after of few changes to mplfinance, is to do a release sometime in December (Jan at latest).

**Comment by DanielGoldfarb** [comment]
https://pypi.org/project/mplfinance/
