### ISSUE TITLE
port yahoo url fix

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/mpl_finance#4]
Port https://github.com/matplotlib/matplotlib/pull/4997 to this project.

**Comment by tacaswell** [comment]
Or pick up https://pypi.python.org/pypi/yahoo-finance as an (optional?) dependency.

**Comment by akkana** [comment]
Is the change still needed? Both URLs seem to work for me now via quotes_historical_yahoo_ohlc, but I might not be using all the relevant options.

**Comment by hajderr** [comment]
I cannot seem to get the URL working, I guess this needs to be changed still?
